language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

script:

    - ./build/tools/phpunit.phar --configuration ./build/travis-ci.xml
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false
